import type { FigmaNode } from "../types/figmaNode";
import { type TokenResolveContext } from "../tokens/resolveToken";
export interface MapComponentInput {
    rawSpec: string;
    name?: string;
    x?: number;
    y?: number;
    width?: number;
    height?: number;
    variant?: string;
    emphasis?: string;
    widthMode?: string;
    intent?: string;
    tone?: string;
    color?: string;
    fill?: string;
    shape?: string;
    size?: string;
    state?: string;
    selected?: boolean;
    iconOnly?: boolean;
    fullWidth?: boolean;
    block?: boolean;
    loading?: boolean | "auto";
    loadingText?: string;
    loadingIcon?: string;
    disabled?: boolean;
    readOnly?: boolean;
    clearable?: boolean;
    value?: string;
    defaultValue?: string;
    placeholder?: string;
    maxLength?: number;
    minLength?: number;
    autoComplete?: string;
    autoFocus?: boolean;
    pattern?: string;
    inputMode?: string;
    onFocus?: string;
    onBlur?: string;
    onPaste?: string;
    autoCapitalize?: string;
    autoCorrect?: string;
    onKeyDown?: string;
    onKeyUp?: string;
    onCompositionStart?: string;
    onCompositionEnd?: string;
    onClick?: string;
    step?: number;
    id?: string;
    enterKeyHint?: string;
    onChange?: string;
    clearIcon?: string;
    onlyShowClearWhenFocus?: boolean;
    onClear?: string;
    onEnterPress?: string;
    min?: number;
    max?: number;
    activeKey?: string;
    defaultActiveKey?: string;
    activeLineMode?: "auto" | "full" | "fixed";
    stretch?: boolean;
    direction?: "ltr" | "rtl";
    autoScroll?: boolean;
    title?: string;
    header?: string;
    mode?: "default" | "card";
    layout?: "vertical" | "horizontal";
    description?: string;
    prefix?: string;
    extra?: string;
    help?: string;
    footer?: string;
    left?: string;
    right?: string;
    back?: string;
    clickable?: boolean;
    arrowIcon?: boolean | string;
    arrow?: boolean | string;
    visible?: boolean;
    image?: string;
    content?: string;
    actions?: string;
    onAction?: string;
    onClose?: string;
    closeOnAction?: boolean;
    closeOnMaskClick?: boolean;
    position?: "top" | "bottom" | "left" | "right" | "center";
    closeOnSwipe?: boolean;
    showCloseButton?: boolean;
    mask?: boolean;
    icon?: "success" | "fail" | "loading" | string;
    duration?: number;
    maskClickable?: boolean;
    backIcon?: boolean | string;
    backArrow?: boolean | string;
    onBack?: string;
    forceRender?: boolean;
    destroyOnClose?: boolean;
    safeArea?: boolean;
    badge?: string;
    required?: boolean;
    hidden?: boolean;
    childElementPosition?: "normal" | "right";
    hasFeedback?: boolean;
    noStyle?: boolean;
    form?: string;
    children?: string;
    onMouseDown?: string;
    onMouseUp?: string;
    onTouchStart?: string;
    onTouchEnd?: string;
    cssTextColor?: string;
    cssBackgroundColor?: string;
    cssBorderRadius?: string;
    cssBorderWidth?: string;
    cssBorderStyle?: string;
    cssBorderColor?: string;
    cssFixedActiveLineWidth?: string;
    cssActiveLineHeight?: string;
    cssActiveLineBorderRadius?: string;
    cssTitleFontSize?: string;
    cssContentPadding?: string;
    cssActiveTitleColor?: string;
    cssActiveLineColor?: string;
    cssActiveBackgroundColor?: string;
    cssAlignItems?: string;
    cssBorderBottom?: string;
    cssBorderInner?: string;
    cssBorderTop?: string;
    cssExtraMaxWidth?: string;
    cssFontSize?: string;
    cssHeaderFontSize?: string;
    cssPaddingLeft?: string;
    cssPaddingRight?: string;
    cssPrefixPaddingRight?: string;
    cssPrefixWidth?: string;
    cssHeight?: string;
    cssZIndex?: string;
    cssMaxWidth?: string;
    cssMinWidth?: string;
    iconPosition?: "left" | "right";
    role?: string;
    label?: string;
    type?: string;
    tokenContext: TokenResolveContext;
}
export declare const mapComponent: (input: MapComponentInput) => FigmaNode;
