import type { ComponentIntent, SectionKey } from "./designPromptGrammar";

interface PlacementRule {
  section: SectionKey;
  order: number;
}

export const componentPlacementRules: Record<ComponentIntent, PlacementRule> = {
  title: { section: "header", order: 10 },
  subtitle: { section: "header", order: 20 },
  "helper-text": { section: "form", order: 40 },
  "email-input": { section: "form", order: 10 },
  "password-input": { section: "form", order: 20 },
  "text-input": { section: "form", order: 30 },
  "primary-action": { section: "action", order: 10 },
  "secondary-action": { section: "action", order: 20 },
  "filter-action": { section: "filter", order: 10 },
  "status-text": { section: "empty", order: 10 }
};

export const defaultPlacementByType: Record<string, PlacementRule> = {
  text: { section: "content", order: 50 },
  input: { section: "form", order: 50 },
  textarea: { section: "form", order: 55 },
  "text-field": { section: "form", order: 52 },
  "text-area": { section: "form", order: 57 },
  "search-field": { section: "form", order: 58 },
  autocomplete: { section: "form", order: 62 },
  "date-picker": { section: "form", order: 63 },
  "time-picker": { section: "form", order: 64 },
  slider: { section: "form", order: 82 },
  "icon-button": { section: "action", order: 45 },
  "text-button": { section: "action", order: 46 },
  "action-area": { section: "action", order: 48 },
  tab: { section: "filter", order: 47 },
  "pagination-dots": { section: "filter", order: 66 },
  "page-counter": { section: "filter", order: 67 },
  list: { section: "list", order: 40 },
  cell: { section: "list", order: 48 },
  "nav-bar": { section: "header", order: 5 },
  "tab-bar": { section: "footer", order: 5 },
  form: { section: "form", order: 5 },
  "top-navigation": { section: "filter", order: 30 },
  "bottom-navigation": { section: "filter", order: 31 },
  category: { section: "filter", order: 32 },
  snackbar: { section: "action", order: 65 },
  "section-message": { section: "action", order: 66 },
  "push-badge": { section: "action", order: 67 },
  loading: { section: "action", order: 76 },
  "progress-indicator": { section: "action", order: 81 },
  "progress-tracker": { section: "action", order: 82 },
  menu: { section: "modal", order: 58 },
  popup: { section: "modal", order: 59 },
  "bottom-sheet": { section: "modal", order: 61 },
  "list-cell": { section: "list", order: 48 },
  "list-card": { section: "list", order: 49 },
  accordion: { section: "list", order: 56 },
  "content-badge": { section: "list", order: 57 },
  "play-badge": { section: "list", order: 58 },
  "fallback-view": { section: "list", order: 61 },
  "section-header": { section: "content", order: 10 },
  thumbnail: { section: "content", order: 20 },
  avatar: { section: "content", order: 21 },
  "avatar-group": { section: "content", order: 22 },
  "framed-style": { section: "content", order: 88 },
  select: { section: "form", order: 60 },
  "check-mark": { section: "form", order: 68 },
  checkbox: { section: "form", order: 70 },
  radio: { section: "form", order: 75 },
  switch: { section: "form", order: 80 },
  label: { section: "form", order: 20 },
  "form-field": { section: "form", order: 40 },
  button: { section: "action", order: 50 },
  "filter-button": { section: "filter", order: 50 },
  tabs: { section: "content", order: 60 },
  tag: { section: "content", order: 70 },
  badge: { section: "content", order: 75 },
  chip: { section: "filter", order: 55 },
  "segmented-control": { section: "content", order: 78 },
  pagination: { section: "filter", order: 65 },
  divider: { section: "content", order: 80 },
  toolbar: { section: "filter", order: 60 },
  table: { section: "list", order: 40 },
  "table-row": { section: "list", order: 45 },
  "list-row": { section: "list", order: 50 },
  "metadata-row": { section: "list", order: 55 },
  "empty-state": { section: "list", order: 60 },
  skeleton: { section: "list", order: 65 },
  spinner: { section: "action", order: 75 },
  progress: { section: "action", order: 80 },
  modal: { section: "modal", order: 40 },
  dialog: { section: "modal", order: 50 },
  popover: { section: "modal", order: 55 },
  tooltip: { section: "modal", order: 57 },
  sheet: { section: "modal", order: 60 },
  card: { section: "content", order: 85 },
  container: { section: "content", order: 90 },
  panel: { section: "modal", order: 52 },
  toast: { section: "action", order: 70 },
  alert: { section: "action", order: 60 }
};
