export type ScreenType = "button-inspection" | "input-inspection";
export type LayoutDensity = "comfortable" | "compact";
export type ScreenState = "empty" | "loading" | "filled" | "error";
export type DataComplexity = "low" | "medium" | "high";
export type SectionKey = "preview" | "header" | "filter" | "content" | "form" | "list" | "detail" | "action" | "footer" | "empty" | "modal";
export type ComponentIntent = "title" | "subtitle" | "helper-text" | "text-input" | "primary-action" | "secondary-action";
export type DesignPromptComponentType = "text" | "input" | "button" | "filter-button";
export type ExtendedDesignPromptComponentType = DesignPromptComponentType | "textarea" | "select" | "check-mark" | "checkbox" | "radio" | "switch" | "tabs" | "tab" | "modal" | "dialog" | "snackbar" | "menu" | "popup" | "bottom-sheet" | "tag" | "badge" | "chip" | "icon-button" | "text-button" | "action-area" | "pagination" | "pagination-dots" | "page-counter" | "list" | "cell" | "nav-bar" | "tab-bar" | "form" | "table" | "list-cell" | "list-row" | "list-card" | "fallback-view" | "toast" | "alert" | "section-message" | "push-badge" | "form-field" | "label" | "divider" | "card" | "container" | "toolbar" | "section-header" | "thumbnail" | "avatar" | "avatar-group" | "content-badge" | "play-badge" | "accordion" | "segmented-control" | "skeleton" | "spinner" | "loading" | "progress" | "progress-indicator" | "progress-tracker" | "sheet" | "table-row" | "metadata-row" | "popover" | "tooltip" | "panel" | "top-navigation" | "bottom-navigation" | "category" | "autocomplete" | "text-field" | "text-area" | "search-field" | "slider" | "date-picker" | "time-picker" | "framed-style";
export interface GrammarComponent {
    type?: ExtendedDesignPromptComponentType | string;
    component?: ExtendedDesignPromptComponentType;
    name?: string;
    label?: string;
    value?: string;
    defaultValue?: string;
    placeholder?: string;
    role?: string;
    header?: string;
    mode?: "default" | "card";
    layout?: "vertical" | "horizontal";
    intent?: ComponentIntent;
    section?: SectionKey;
    variant?: string;
    emphasis?: "primary" | "secondary" | "tertiary" | "destructive";
    width?: "hug" | "full";
    intent?: ComponentIntent | "default" | "error" | "success";
    color?: "default" | "primary" | "success" | "warning" | "danger";
    fill?: "solid" | "outline" | "none";
    shape?: "default" | "rounded" | "rectangular";
    block?: boolean;
    disabled?: boolean;
    readOnly?: boolean;
    clearable?: boolean;
    tone?: "default" | "success" | "warning" | "danger" | "info";
    size?: "mini" | "small" | "middle" | "large" | "sm" | "md" | "lg";
    state?: "default" | "enabled" | "hover" | "pressed" | "disabled" | "focus" | "focused" | "error" | "positive" | "readOnly" | "readonly" | "selected" | "active" | "open" | "closing" | "loading";
    selected?: boolean;
    iconOnly?: boolean;
    fullWidth?: boolean;
    loading?: boolean | "auto";
    loadingText?: string;
    loadingIcon?: string;
    iconPosition?: "left" | "right";
    onClick?: string;
    children?: string;
    title?: string;
    description?: string;
    prefix?: string;
    extra?: string;
    help?: string;
    footer?: string;
    left?: string;
    right?: string;
    back?: string;
    clickable?: boolean;
    arrowIcon?: boolean | string;
    arrow?: boolean | string;
    onMouseDown?: string;
    onMouseUp?: string;
    onTouchStart?: string;
    onTouchEnd?: string;
    id?: string;
    form?: string;
    "--text-color"?: string;
    "--background-color"?: string;
    "--border-radius"?: string;
    "--border-width"?: string;
    "--border-style"?: string;
    "--border-color"?: string;
    maxLength?: number;
    minLength?: number;
    autoComplete?: string;
    autoFocus?: boolean;
    pattern?: string;
    inputMode?: string;
    onFocus?: string;
    onBlur?: string;
    onPaste?: string;
    autoCapitalize?: string;
    autoCorrect?: string;
    onKeyDown?: string;
    onKeyUp?: string;
    onCompositionStart?: string;
    onCompositionEnd?: string;
    step?: number;
    enterKeyHint?: string;
    onChange?: string;
    clearIcon?: string;
    onlyShowClearWhenFocus?: boolean;
    onClear?: string;
    onEnterPress?: string;
    min?: number;
    max?: number;
    visible?: boolean;
    image?: string;
    content?: string;
    actions?: string;
    onAction?: string;
    onClose?: string;
    closeOnAction?: boolean;
    closeOnMaskClick?: boolean;
    position?: "top" | "bottom" | "left" | "right" | "center";
    closeOnSwipe?: boolean;
    showCloseButton?: boolean;
    mask?: boolean;
    icon?: "success" | "fail" | "loading" | string;
    duration?: number;
    maskClickable?: boolean;
    backIcon?: boolean | string;
    backArrow?: boolean | string;
    onBack?: string;
    activeKey?: string;
    defaultActiveKey?: string;
    safeArea?: boolean;
    badge?: string;
    required?: boolean;
    hidden?: boolean;
    childElementPosition?: "normal" | "right";
    hasFeedback?: boolean;
    noStyle?: boolean;
    activeLineMode?: "auto" | "full" | "fixed";
    stretch?: boolean;
    direction?: "ltr" | "rtl";
    autoScroll?: boolean;
    forceRender?: boolean;
    destroyOnClose?: boolean;
    "--fixed-active-line-width"?: string;
    "--active-line-height"?: string;
    "--active-line-border-radius"?: string;
    "--title-font-size"?: string;
    "--content-padding"?: string;
    "--active-title-color"?: string;
    "--active-line-color"?: string;
    "--active-background-color"?: string;
    "--align-items"?: string;
    "--border-bottom"?: string;
    "--border-inner"?: string;
    "--border-top"?: string;
    "--extra-max-width"?: string;
    "--font-size"?: string;
    "--header-font-size"?: string;
    "--padding-left"?: string;
    "--padding-right"?: string;
    "--prefix-padding-right"?: string;
    "--prefix-width"?: string;
    "--height"?: string;
    "--z-index"?: string;
    "--max-width"?: string;
    "--min-width"?: string;
}
export declare const resolveComponentType: (component: GrammarComponent) => ExtendedDesignPromptComponentType;
export interface GrammarDesignPrompt {
    screen: ScreenType | string;
    purpose?: string;
    theme: string;
    density?: LayoutDensity;
    sections?: SectionKey[];
    primaryAction?: string;
    secondaryAction?: string;
    dataComplexity?: DataComplexity;
    state?: ScreenState;
    components: GrammarComponent[];
}
export declare const normalizePrompt: (prompt: GrammarDesignPrompt) => Required<Omit<GrammarDesignPrompt, "sections" | "purpose" | "primaryAction" | "secondaryAction">> & Pick<GrammarDesignPrompt, "sections" | "purpose" | "primaryAction" | "secondaryAction">;
export declare const validatePromptGrammar: (prompt: GrammarDesignPrompt) => {
    valid: boolean;
    errors: string[];
};
