// Generated from official Wanted Montage docs. Do not edit by hand.
export const wantedBaselineCategories = {
    "Actions": [
        "Action Area",
        "Button",
        "Chip",
        "Icon Button",
        "Text Button"
    ],
    "Contents": [
        "Accordion",
        "Avatar",
        "Avatar Group",
        "Card",
        "Content Badge",
        "List Card",
        "List Cell",
        "Play Badge",
        "Section Header",
        "Table",
        "Thumbnail"
    ],
    "Feedback": [
        "Alert",
        "Fallback View",
        "Push Badge",
        "Section Message",
        "Snackbar",
        "Toast"
    ],
    "Loading": [
        "Loading",
        "Skeleton"
    ],
    "Navigations": [
        "Bottom Navigation",
        "Category",
        "Page Counter",
        "Pagination",
        "Pagination Dots",
        "Progress Indicator",
        "Progress Tracker",
        "Tab",
        "Top Navigation"
    ],
    "Presentation": [
        "Autocomplete",
        "Bottom Sheet",
        "Menu",
        "Popover",
        "Popup",
        "Tooltip"
    ],
    "Selection and input": [
        "Check Mark",
        "Checkbox",
        "Date Picker",
        "Filter Button",
        "Framed Style",
        "Radio",
        "Search Field",
        "Segmented Control",
        "Select",
        "Slider",
        "Switch",
        "Text Area",
        "Text Field",
        "Time Picker"
    ]
};
export const wantedBaselineToRegistry = {
    "Action Area": "ActionArea",
    "Button": "Button",
    "Chip": "Chip",
    "Icon Button": "IconButton",
    "Text Button": "TextButton",
    "Accordion": "Accordion",
    "Avatar": "Avatar",
    "Avatar Group": "AvatarGroup",
    "Card": "Card",
    "Content Badge": "ContentBadge",
    "List Card": "ListCard",
    "List Cell": "ListCell",
    "Play Badge": "PlayBadge",
    "Section Header": "SectionHeader",
    "Table": "Table",
    "Thumbnail": "Thumbnail",
    "Alert": "Alert",
    "Fallback View": "FallbackView",
    "Push Badge": "PushBadge",
    "Section Message": "SectionMessage",
    "Snackbar": "Snackbar",
    "Toast": "Toast",
    "Loading": "Loading",
    "Skeleton": "Skeleton",
    "Bottom Navigation": "BottomNavigation",
    "Category": "Category",
    "Page Counter": "PageCounter",
    "Pagination": "Pagination",
    "Pagination Dots": "PaginationDots",
    "Progress Indicator": "ProgressIndicator",
    "Progress Tracker": "ProgressTracker",
    "Tab": "Tab",
    "Top Navigation": "TopNavigation",
    "Autocomplete": "Autocomplete",
    "Bottom Sheet": "BottomSheet",
    "Menu": "Menu",
    "Popover": "Popover",
    "Popup": "Popup",
    "Tooltip": "Tooltip",
    "Check Mark": "CheckMark",
    "Checkbox": "Checkbox",
    "Date Picker": "DatePicker",
    "Filter Button": "FilterButton",
    "Framed Style": "FramedStyle",
    "Radio": "Radio",
    "Search Field": "SearchField",
    "Segmented Control": "SegmentedControl",
    "Select": "Select",
    "Slider": "Slider",
    "Switch": "Switch",
    "Text Area": "TextArea",
    "Text Field": "TextField",
    "Time Picker": "TimePicker"
};
